# Generated by Django 4.0.2 on 2022-03-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_title_national_foods_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_birth', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
