# Generated by Django 4.0.2 on 2022-03-12 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_posts_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='date',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='full_text',
        ),
    ]
