# Generated by Django 4.0.2 on 2022-03-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_posts_date_remove_posts_full_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='news',
            field=models.CharField(max_length=250, verbose_name='Информация'),
        ),
    ]
