# Generated by Django 4.0.2 on 2022-03-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_posts_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('news', models.CharField(max_length=250, verbose_name='Информация')),
                ('file', models.ImageField(upload_to='')),
                ('author', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
