# Generated by Django 4.0.2 on 2022-03-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_post_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Тақырып')),
                ('is_published', models.BooleanField(default=True, verbose_name='Шығарылым')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='news',
            field=models.CharField(max_length=500, verbose_name='Информация'),
        ),
    ]
