# Generated by Django 4.0.2 on 2022-04-14 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_posts1_delete_posts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts1',
        ),
    ]
