# Generated by Django 4.0.2 on 2022-04-15 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_posts1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts1',
            new_name='Postperson',
        ),
    ]
