# Generated by Django 4.0.2 on 2022-04-16 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_postpersons_delete_postperson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpersons',
            name='password',
        ),
    ]
