# Generated by Django 4.0.2 on 2022-04-18 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_postpersons_delete_postperson'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postpersons',
            new_name='Postperson',
        ),
    ]
