# Generated by Django 4.0.2 on 2022-04-18 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_rename_postpersons_postperson'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postperson',
            new_name='Postusers',
        ),
    ]
