# Generated by Django 4.0.4 on 2022-04-22 04:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_rename_postperson_postusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postusers',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='postusers',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='Last name'),
        ),
    ]
