# Generated by Django 4.0.4 on 2022-04-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_postusers_first_name_alter_postusers_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='postusers',
            name='number',
            field=models.IntegerField(default=1, verbose_name='call_number'),
        ),
        migrations.AlterField(
            model_name='postusers',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
    ]
